import { Router } from "express";

import userRoutes from "./userRoutes";
import authRoutes from "./authRoutes";
import settingRoutes from "./settingRoutes";
import contactRoutes from "./contactRoutes";
import ticketRoutes from "./ticketRoutes";
import whatsappRoutes from "./whatsappRoutes";
import messageRoutes from "./messageRoutes";
import whatsappSessionRoutes from "./whatsappSessionRoutes";
import queueRoutes from "./queueRoutes";
import companyRoutes from "./companyRoutes";
import companyModuleRoutes from "./companyModuleRoutes";
import planRoutes from "./planRoutes";
import ticketNoteRoutes from "./ticketNoteRoutes";
import quickMessageRoutes from "./quickMessageRoutes";
import helpRoutes from "./helpRoutes";
import helpArticleRoutes from "./helpArticleRoutes";
import dashboardRoutes from "./dashboardRoutes";
import queueOptionRoutes from "./queueOptionRoutes";
import scheduleRoutes from "./scheduleRoutes";
import tagRoutes from "./tagRoutes";
import contactListRoutes from "./contactListRoutes";
import contactListItemRoutes from "./contactListItemRoutes";
import campaignRoutes from "./campaignRoutes";
import campaignSettingRoutes from "./campaignSettingRoutes";
import announcementRoutes from "./announcementRoutes";
import chatRoutes from "./chatRoutes";
import invoiceRoutes from "./invoicesRoutes";
import subscriptionRoutes from "./subScriptionRoutes";
import ticketTagRoutes from "./ticketTagRoutes";
import filesRoutes from "./filesRoutes";
import promptRoutes from "./promptRouter";
import queueIntegrationRoutes from "./queueIntegrationRoutes";
import forgotsRoutes from "./forgotPasswordRoutes";
import flowDefaultRoutes from "./flowDefaultRoutes";
import flowBuilder from "./flowBuilderRoutes";
import flowCampaignRoutes from "./flowCampaignRoutes";
import taskRoutes from "./taskRoutes";
import aiRoutes from "./aiRoutes";
import mercadoPagoRoutes from "./mercadoPagoRoutes";
import gupshupWebhookRoutes from "./gupshupWebhookRoutes";
import gupshupValidationRoutes from "./gupshupValidationRoutes";
import formRoutes from "./formRoutes";
import userQuickButtonRoutes from "./userQuickButtonRoutes";
import userAppointmentRoutes from "./userAppointmentRoutes";
import translationRoutes from "./translationRoutes";
import customProposalRoutes from "./customProposalRoutes";
import instagramRoutes from "./instagramRoutes";
import productRoutes from "./productRoutes";
import mesaRoutes from "./mesaRoutes";
import moduleRoutes from "./moduleRoutes";
import printDeviceRoutes from "./printDeviceRoutes";
import deliveryRoutes from "./deliveryRoutes";
import appointmentServiceRoutes from "./appointmentServiceRoutes";
import appointmentRoutes from "./appointmentRoutes";

const routes = Router();

routes.use(instagramRoutes);


routes.use(userRoutes);
routes.use("/auth", authRoutes);
routes.use(settingRoutes);
routes.use(contactRoutes);
routes.use(ticketRoutes);
routes.use(whatsappRoutes);
routes.use(messageRoutes);
routes.use(messageRoutes);
routes.use(whatsappSessionRoutes);
routes.use(queueRoutes);
routes.use(companyRoutes);
routes.use(companyModuleRoutes);
routes.use(planRoutes);
routes.use(ticketNoteRoutes);
routes.use(quickMessageRoutes);
routes.use(helpRoutes);
routes.use(helpArticleRoutes);
routes.use(dashboardRoutes);
routes.use(queueOptionRoutes);
routes.use(scheduleRoutes);
routes.use(tagRoutes);
routes.use(contactListRoutes);
routes.use(contactListItemRoutes);
routes.use(campaignRoutes);
routes.use(campaignSettingRoutes);
routes.use(announcementRoutes);
routes.use(chatRoutes);
routes.use(subscriptionRoutes);
routes.use(invoiceRoutes);
routes.use(ticketTagRoutes);
routes.use(filesRoutes);
routes.use(promptRoutes);
routes.use(queueIntegrationRoutes);
routes.use(forgotsRoutes);

routes.use(flowDefaultRoutes);
routes.use(flowBuilder)
routes.use(flowCampaignRoutes)
routes.use(taskRoutes);
routes.use(aiRoutes);
routes.use(mercadoPagoRoutes);
routes.use(gupshupWebhookRoutes);
routes.use(gupshupValidationRoutes);
routes.use(formRoutes);
routes.use(userQuickButtonRoutes);
routes.use(userAppointmentRoutes);
routes.use(translationRoutes);
routes.use(customProposalRoutes);
routes.use(productRoutes);
routes.use(mesaRoutes);
routes.use(moduleRoutes);
routes.use(printDeviceRoutes);
routes.use(deliveryRoutes);
routes.use(appointmentServiceRoutes);
routes.use(appointmentRoutes);

export default routes;
